[[main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 1

[[main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2
    type = "blog"

[[main]]
    identifier = "homeserver"
    name = "Home Server"
    url = "/homeserver/"
    weight = 3
    type = "docs"