[[main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 1

[[main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2
    type = "page"

[[main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 3
    type = "book"